- name: "show remote environment"
  shell: env

- name: "copy backend binaries"
  become: yes
  synchronize:
    src: ../backend/dist
    dest: /home/ubuntu/app
    recursive: true

- name: "copy node_modules"
  become: yes
  synchronize:
    src: ../backend/node_modules
    dest: /home/ubuntu/app
    recursive: true

- name: Start Server
  become: true
  command: pm2 start npm --name backend -- start
  environment:
     ENVIRONMENT: production
     TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
     TYPEORM_MIGRATIONS_DIR: "./migrations"
     TYPEORM_MIGRATIONS: "./migrations/*.js"
     TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
     TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
     TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
     TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
     TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
     TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
